/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.frontend;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import lab.backend.LibrarianRole;
import javax.swing.JOptionPane;
import java.util.TimeZone;
import lab.backend.RepeatedIdException;

/**
 *
 * @author User
 */
public class BorrowBookWindow extends javax.swing.JFrame implements Node {

    private Node parent;

    public BorrowBookWindow(Node parent) {
        initComponents();
        this.setTitle("Borrow Book");
        this.parent = parent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        bookId = new javax.swing.JTextField();
        borrowDate = new com.toedter.calendar.JDateChooser();
        borrowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 255, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Id");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(0, 255, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Book Id");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(0, 255, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Borrow Date");
        jLabel3.setOpaque(true);

        studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdActionPerformed(evt);
            }
        });

        bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIdActionPerformed(evt);
            }
        });

        borrowButton.setBackground(new java.awt.Color(0, 0, 0));
        borrowButton.setForeground(new java.awt.Color(255, 255, 255));
        borrowButton.setText("Borrow");
        borrowButton.setOpaque(true);
        borrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentId)
                    .addComponent(bookId)
                    .addComponent(borrowDate, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(borrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentId, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bookId)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                    .addComponent(borrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(borrowDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdActionPerformed

    private void bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIdActionPerformed

    private boolean isFieldEmpty() {

        //String.valueOf(borrowDate.getDate()).isBlank() --> didnot Work.
        if (bookId.getText().isBlank() || studentId.getText().isBlank() || borrowDate.getDate() == null) {
            return true;
        }

        return false;
    }

    private LocalDate fromStringTOLocalDate(String s) {
        LocalDate borrowDateLocal;
        //borrowDateLocal.withDayOfMonth();
        return null;
    }

    private void clear() {
        studentId.setText("");
        bookId.setText("");
        borrowDate.setDate(null);
    }

    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowButtonActionPerformed
        // TODO add your handling code here:

        //first: check if some fields are empty.
        if (isFieldEmpty()) {
            JOptionPane.showMessageDialog(null, "Some fields are empty");
            clear();
            return;
        }

//        this.setVisible(false);
        LibrarianRoleWindow parentFrame = (LibrarianRoleWindow) parent;
//        parentFrame.setVisible(true);

        //TODO check if the BookId is repeated.
        String bookID = bookId.getText();
        String studentID = studentId.getText();
        //error cannot convert from Date to Local Date.
        //LocalDate borrowDateTime = (LocalDate) (borrowDate.getDate());

//      Date input = new Date();
//      System.out.println(input);
//      LocalDate date1 = borrowDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//      System.out.println(date);
        LocalDate date = LocalDate.ofInstant(borrowDate.getDate().toInstant(), ZoneId.systemDefault());

        try {
            int result = parentFrame.getLbRole().borrowBook(studentID, bookID, date);

            if (result == -1) {
                JOptionPane.showMessageDialog(null, "No Books are found with id = " + bookID);

            } //third: All the copies of the book were borrowed and no copies left.
            else if (result == 1) {
                JOptionPane.showMessageDialog(null, "The student with id = " + studentID
                        + " has already borrowed a copy of the book with id = " + bookID + " and hasn't returned it yet.");

            } else if (result == 0) {
                JOptionPane.showMessageDialog(null, "All copies of the book with id = " + bookID
                        + " have been borrowed and no copy is left for the student with id = " + studentID);

            } else {
                //Fourth: Successfully added.
                JOptionPane.showMessageDialog(null, "The student with id = " + studentID + " has successfully borrowed a copy of the book with id = " + bookID);
            }
            clear();

        } catch (RepeatedIdException rie) {
            JOptionPane.showMessageDialog(null, "The student with id = " + studentID
                    + " has already borrowed a copy of the book with id = " + bookID + " and hasn't returned it yet.");

        }


    }//GEN-LAST:event_borrowButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        this.setVisible(false);
        LibrarianRoleWindow parentFrame = (LibrarianRoleWindow) parent;
        parentFrame.setVisible(true);
        clear();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookId;
    private javax.swing.JButton borrowButton;
    private com.toedter.calendar.JDateChooser borrowDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField studentId;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getNodeParent() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean hasNodeParent() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
